-- ==============================================================================
-- ABDULGHANI AL-SHIBAMI PORTFOLIO PLATFORM — CANONICAL AUTHENTIC SEED DATA
-- Target: Supabase / PostgreSQL 15+
-- Strictly authentic records: 5 Canonical Projects, 5 Authentic Certificates
-- ==============================================================================

-- 1. Profiles Table Seed
INSERT INTO public.profiles (
    id,
    full_name_en,
    full_name_ar,
    headline_en,
    headline_ar,
    bio_en,
    bio_ar,
    avatar_url,
    resume_url,
    email,
    location_en,
    location_ar
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'Abdulghani Al-Shibami',
    'عبدالغني علي محمد أحمد الشبامي',
    'AI Engineer & Software Developer',
    'مهندس ذكاء اصطناعي ومطور برمجيات',
    'Information Technology student and software engineer from Yemen passionate about artificial intelligence, system architecture, and building production-grade solutions for real-world enterprise operations.',
    'طالب تكنولوجيا معلومات ومهندس برمجيات من اليمن، شغوف بالذكاء الاصطناعي ومعمارية الأنظمة وبناء حلول برمجية مؤسسية واقعية وموثوقة.',
    '/images/profile/abdulghani-portrait.webp',
    '/docs/Abdulghani_Al-Shibami_CV.pdf',
    'samyemen987@gmail.com',
    'Sana''a, Yemen',
    'صنعاء، اليمن'
)
ON CONFLICT (id) DO UPDATE SET
    full_name_en = EXCLUDED.full_name_en,
    full_name_ar = EXCLUDED.full_name_ar,
    headline_en = EXCLUDED.headline_en,
    headline_ar = EXCLUDED.headline_ar,
    bio_en = EXCLUDED.bio_en,
    bio_ar = EXCLUDED.bio_ar,
    avatar_url = EXCLUDED.avatar_url,
    resume_url = EXCLUDED.resume_url,
    email = EXCLUDED.email,
    location_en = EXCLUDED.location_en,
    location_ar = EXCLUDED.location_ar;

-- 2. Project Categories Seed
INSERT INTO public.project_categories (id, slug, name_en, name_ar, display_order) VALUES
    ('10000000-0000-0000-0000-000000000001', 'enterprise-desktop', 'Enterprise & Desktop Software', 'برمجيات سطح المكتب والمؤسسات', 1),
    ('10000000-0000-0000-0000-000000000002', 'ai-research', 'AI & Algorithmic Research', 'الذكاء الاصطناعي والبحث الخوارزمي', 2),
    ('10000000-0000-0000-0000-000000000003', 'e-commerce', 'Modern Web & E-Commerce', 'منصات الويب والمتاجر الإلكترونية', 3),
    ('10000000-0000-0000-0000-000000000004', 'academic-systems', 'Academic Platforms & Portals', 'المنصات الأكاديمية والأنظمة الجامعية', 4)
ON CONFLICT (slug) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    display_order = EXCLUDED.display_order;

-- 3. Technologies Master Table Seed
INSERT INTO public.technologies (name, category, icon_name) VALUES
    ('C#', 'language', 'csharp'),
    ('WinForms', 'framework', 'windows'),
    ('Oracle Database', 'database', 'database'),
    ('Python', 'language', 'python'),
    ('PyQt6', 'framework', 'layout'),
    ('Next.js', 'framework', 'globe'),
    ('TypeScript', 'language', 'code'),
    ('PostgreSQL', 'database', 'database'),
    ('Vanilla JS', 'language', 'javascript'),
    ('Modern CSS3', 'tool', 'palette'),
    ('HTML5', 'tool', 'file-text'),
    ('Tailwind CSS', 'tool', 'wind'),
    ('ITIL Operations', 'tool', 'activity'),
    ('RBAC Security', 'tool', 'shield')
ON CONFLICT (name) DO NOTHING;

-- 4. Projects Master Table Seed (The 5 Canonical Authentic Projects)
INSERT INTO public.projects (
    id,
    slug,
    category_id,
    title_en,
    title_ar,
    short_desc_en,
    short_desc_ar,
    problem_en,
    problem_ar,
    solution_en,
    solution_ar,
    architecture_en,
    architecture_ar,
    year,
    status,
    featured,
    display_order,
    github_url,
    live_url,
    demo_type,
    demo_config,
    thumbnail_url
) VALUES
    (
        '20000000-0000-0000-0000-000000000001',
        'campus-it-tracker',
        '10000000-0000-0000-0000-000000000001',
        'Campus IT Infrastructure Tracker',
        'نظام تتبع وإدارة البنية التحتية لتكنولوجيا المعلومات بالجامعة',
        'Enterprise-grade campus network node topology mapping, ITIL incident lifecycle, and Oracle relational database architecture.',
        'نظام مؤسسي متكامل لتتبع وإدارة شبكات الحرم الجامعي وتذاكر الدعم الفني المبني بـ C# وقواعد بيانات Oracle.',
        'Universities struggle with untracked hardware failures, uncoordinated maintenance dispatches, and lack of visual network topology during outages.',
        'تواجه الجامعات صعوبة بالغة في تتبع الأعطال وتنسيق فرق الصيانة وانعدام الرؤية الطوبولوجية للشبكة أثناء الانقطاعات.',
        'Built an offline-resilient desktop management workstation with dynamic GDI+ topology visualization and full ITIL incident ticketing lifecycle.',
        'تطوير محطة عمل مكتبية موثوقة تعمل بدون إنترنت مع رسم مرئي لطوبولوجيا الشبكة ونظام متكامل لتذاكر الأعطال وفق منهجية ITIL.',
        'Three-Tier Architecture: Presentation (WinForms / GDI+), Business Logic (C# .NET), Data Access (Oracle ODP.NET with parameterized queries and RBAC guards).',
        'معمارية ثلاثية الطبقات: طبقة العرض (WinForms / GDI+)، منطق الأعمال (C# .NET)، والوصول للبيانات (Oracle ODP.NET باستعلامات مأمونة وتحكم في الصلاحيات).',
        2024,
        'Production Ready',
        true,
        1,
        'https://github.com/Abdulghani780/Campuse-IT-Tracker',
        NULL,
        'interactive_simulation',
        '{"simulationId": "campus-it-tracker", "mode": "standalone"}'::jsonb,
        '/images/projects/campus-card.png'
    ),
    (
        '20000000-0000-0000-0000-000000000002',
        'metaalgorithm-lab',
        '10000000-0000-0000-0000-000000000002',
        'MetaAlgorithm Lab',
        'مختبر الخوارزميات الفوقية والتحليل التجريبي',
        'Scientific algorithm benchmarking, time-complexity visualization, and metaheuristic optimization simulation suite.',
        'بيئة حاسوبية علمية متقدمة لدراسة وتحليل كفاءة الخوارزميات وتوليد المقارنات الإحصائية والتعقيد الحسابي.',
        'Understanding theoretical algorithm behavior under varying dataset distributions requires rigorous experimental telemetry rather than static equations.',
        'فهم سلوك الخوارزميات النظري عند اختلاف توزيعات البيانات يتطلب قياسات تجريبية دقيقة ورسوماً بيانية حية بدلاً من المعادلات المجردة.',
        'Created an interactive desktop analytical workbench featuring step-by-step sorting visualizer, recursion tree inspectors, and real-time execution profiling.',
        'تطوير منصة تحليلية تفاعلية تتضمن محاكاة حية لخوارزميات الترتيب وتحليل شجرة الاستدعاء الذاتي ومقارنة استهلاك الذاكرة والزمن.',
        'Modular PyQt6 analytical dashboard connected to a high-performance Python algorithmic engine with decoupled benchmark runners.',
        'لوحة تحكم معيارية بـ PyQt6 متصلة بمحرك خوارزمي عالي الأداء مع فصل تام بين المنطق الحسابي ورسم الواجهات.',
        2024,
        'Completed',
        true,
        2,
        'https://github.com/Abdulghani780/metaalgorithm-lab',
        NULL,
        'interactive_simulation',
        '{"simulationId": "metaalgorithm-lab", "mode": "standalone"}'::jsonb,
        '/images/projects/meta-card.png'
    ),
    (
        '20000000-0000-0000-0000-000000000003',
        'novatech',
        '10000000-0000-0000-0000-000000000003',
        'NovaTech Storefront',
        'متجر نوفاتيك للحلول التقنية والأجهزة الذكية',
        'Cyber gadgets catalog, high-performance client-side cart engine, real-time search, and tax invoice calculation workstation.',
        'منصة تجارة إلكترونية تفاعلية للأجهزة والحلول التقنية مع سلة تسوق فورية ونظام تصفية دقيق وحساب للفواتير والضرائب.',
        'Traditional web storefronts often load heavy third-party bundles, leading to slow rendering on constrained network connections.',
        'المتاجر التقليدية تعاني من ثقل الحزم البرمجية وبطء الاستجابة في بيئات الاتصال المحدودة.',
        'Architected a lightning-fast, zero-dependency e-commerce storefront with client-side state machine, instant cart drawer, and currency conversion.',
        'بناء متجر إلكتروني فائق السرعة بدون مكتبات خارجية ثقيلة مع إدارة فورية لحالة السلة وتحويل للعملات وحسابات دقيقة.',
        'Vanilla ES6+ State Architecture with Modern CSS3 Grid and Flexbox layouts, persistent localStorage state, and modal invoice generators.',
        'معمارية حالة خفيفة بـ Vanilla JavaScript وتنسيقات CSS3 متقدمة مع مزامنة محلية للسلة وتوليد فوري للفواتير.',
        2024,
        'Active Showcase',
        true,
        3,
        'https://github.com/Abdulghani780/novatech',
        NULL,
        'interactive_simulation',
        '{"simulationId": "novatech", "mode": "standalone"}'::jsonb,
        '/images/projects/novatech/01-storefront-hero.jpg'
    ),
    (
        '20000000-0000-0000-0000-000000000004',
        'cafena',
        '10000000-0000-0000-0000-000000000003',
        'Cafena Specialty Coffee',
        'كافينا للقهوة المختصة',
        'Artisanal coffee experience portal with responsive menu matrix, instant cart tallying, and booking simulation.',
        'منصة تفاعلية عصرية لتجربة القهوة المختصة مع قائمة أصناف غنية وسلة طلبات ذكية وحساب فوري للتكلفة.',
        'Specialty beverage businesses require distinct brand storytelling combined with seamless, frictionless mobile ordering.',
        'تحتاج متاجر الأغذية والمشروبات المتخصصة إلى هوية بصرية متميزة مع تجربة طلب سلسة وسريعة على الهواتف الذكية.',
        'Engineered an immersive, rich editorial coffee house showcase with interactive bean selector, customized roast orders, and instant cart calculation.',
        'بناء تجربة رقمية فاخرة تعكس ثقافة القهوة مع اختيار مخصص لنوع التحميص وحساب سريع للطلبات.',
        'Modern semantic HTML5, responsive CSS Grid layout system, CSS custom properties, and decoupled JavaScript order state orchestrator.',
        'واجهة عصرية بـ HTML5 الدلالي وتنسيقات CSS Grid المتجاوبة مع محرك إدارة طلبات خفيف بلغة جافاسكريبت.',
        2023,
        'Completed',
        true,
        4,
        'https://github.com/Abdulghani780/Cafena',
        NULL,
        'interactive_simulation',
        '{"simulationId": "cafena", "mode": "standalone"}'::jsonb,
        '/images/projects/cafena/01-storefront-hero.jpg'
    ),
    (
        '20000000-0000-0000-0000-000000000005',
        'gp',
        '10000000-0000-0000-0000-000000000004',
        'Graduation Project Portal',
        'منصة إدارة مشاريع التخرج الأكاديمية',
        'Academic project lifecycle system managing student proposal workflows, faculty milestone evaluations, and defense scheduling.',
        'نظام أكاديمي متكامل لإدارة ومتابعة مشاريع التخرج وتنسيق لجان المناقشة وتدقيق تقارير الإنجاز الجامعية.',
        'Academic departments encounter severe operational overhead tracking hundreds of thesis proposals, milestones, and supervisor approvals across spreadsheets.',
        'تعاني الأقسام الجامعية من مشقة بالغة في متابعة مقترحات المشاريع ومسارات الموافقة وتوثيق مراجعات المشرفين بالطرق اليدوية.',
        'Engineered an end-to-end academic portal managing student team formation, proposal triage, supervisor reviews, and automated defense scheduling.',
        'تطوير بوابة أكاديمية شاملة تبدأ من تشكيل الفرق البحثية وتقديم المقترحات وحتى مراجعات لجان التحكيم وجدولة المناقشات.',
        'Full-Stack relational web system with strict role access (Student, Supervisor, Department Head, Committee Reviewer) and audit-logged milestones.',
        'نظام ويب علائقي متعدد الأدوار (طالب، مشرف، رئيس قسم، لجنة تحكيم) مع توثيق زمني كامل لمراحل الإنجاز.',
        2024,
        'Academic Production',
        false,
        5,
        'https://github.com/Abdulghani780/Gp',
        NULL,
        'interactive_simulation',
        '{"simulationId": "gp", "mode": "standalone"}'::jsonb,
        '/images/projects/campus-card.png'
    )
ON CONFLICT (slug) DO UPDATE SET
    title_en = EXCLUDED.title_en,
    title_ar = EXCLUDED.title_ar,
    short_desc_en = EXCLUDED.short_desc_en,
    short_desc_ar = EXCLUDED.short_desc_ar,
    problem_en = EXCLUDED.problem_en,
    problem_ar = EXCLUDED.problem_ar,
    solution_en = EXCLUDED.solution_en,
    solution_ar = EXCLUDED.solution_ar,
    architecture_en = EXCLUDED.architecture_en,
    architecture_ar = EXCLUDED.architecture_ar,
    year = EXCLUDED.year,
    status = EXCLUDED.status,
    featured = EXCLUDED.featured,
    display_order = EXCLUDED.display_order,
    github_url = EXCLUDED.github_url,
    demo_type = EXCLUDED.demo_type,
    demo_config = EXCLUDED.demo_config,
    thumbnail_url = EXCLUDED.thumbnail_url;

-- 5. Experiences Table Seed (Authentic Education & Verified Certificates)
INSERT INTO public.experiences (
    id,
    type,
    title_en,
    title_ar,
    institution_en,
    institution_ar,
    location_en,
    location_ar,
    start_date,
    end_date,
    is_current,
    description_en,
    description_ar,
    display_order
) VALUES
    (
        '30000000-0000-0000-0000-000000000001',
        'education',
        'Bachelor of Information Technology',
        'بكالوريوس في تكنولوجيا المعلومات',
        'University of Modern Sciences (UMS)',
        'جامعة العلوم الحديثة',
        'Sana''a, Yemen',
        'صنعاء، اليمن',
        '2022-09-01',
        NULL,
        true,
        'Specializing in software engineering, database management systems, applied AI integration, and systems design.',
        'تخصص في هندسة البرمجيات وإدارة قواعد البيانات والأنظمة الذكية وتطبيقات الذكاء الاصطناعي.',
        1
    ),
    (
        '30000000-0000-0000-0000-000000000002',
        'certification',
        'International Professional Trainer Certificate (TOT) - Novice Trainer',
        'شهادة تدريب مدربين دولية (TOT) - المستوى المبتدئ',
        'International Board of Certified Trainers (IBCT)',
        'البورد الدولي للمدربين المعتمدين - المقر الرئيسي للشرق الأوسط وشمال أفريقيا',
        'MENA Division',
        'إقليم الشرق الأوسط وشمال أفريقيا',
        '2025-09-01',
        '2025-09-01',
        false,
        'Accreditation as a Professional Certified Trainer under Dutch/European quality standards (Reg No: 150047/NT).',
        'اعتماد كمدرب محترف معتمد وفق معايير الجودة الهولندية والأوروبية برقم قيد دولي معتمد.',
        2
    ),
    (
        '30000000-0000-0000-0000-000000000003',
        'honor',
        'Certificate of Appreciation — Yemen AI Summit 2026',
        'شهادة تقدير ومشاركة — قمة الذكاء الاصطناعي باليمن 2026م',
        'Modern Specialized University & Ministry of Higher Education',
        'الجامعة التخصصية الحديثة ووزارة التعليم العالي',
        'Sana''a, Yemen',
        'صنعاء، اليمن',
        '2026-07-01',
        '2026-07-01',
        false,
        'Awarded for active contribution and innovative research participation in the Yemen AI Summit 2026.',
        'شهادة تقدير لمشاركته الفعالة والقيمة في إنجاح أعمال قمة الذكاء الاصطناعي 2026م.',
        3
    ),
    (
        '30000000-0000-0000-0000-000000000004',
        'certification',
        'Web Development Using AI Tools Professional Workshop',
        'ورشة عمل تطوير المواقع الإلكترونية باستخدام أدوات الذكاء الاصطناعي',
        'University of Modern Sciences (UMS) — Innovation Center',
        'جامعة العلوم الحديثة — مركز الابتكار وريادة الأعمال',
        'Sana''a, Yemen',
        'صنعاء، اليمن',
        '2026-05-04',
        '2026-05-11',
        false,
        'Hands-on professional technical workshop covering generative AI in web systems, automated code scaffolding, and modern UI engineering.',
        'برنامج تدريبي تخصصي في توظيف الذكاء الاصطناعي التوليدي في هندسة الويب وتسريع التطوير البرمجي.',
        4
    ),
    (
        '30000000-0000-0000-0000-000000000005',
        'honor',
        'Innovation and Distinction Shield / Certificate',
        'شهادة التميز والابتكار في ريادة الأعمال التقنية',
        'Center for Innovation and Entrepreneurship (UMS)',
        'مركز الابتكار وريادة الأعمال — جامعة العلوم الحديثة',
        'Sana''a, Yemen',
        'صنعاء، اليمن',
        '2026-05-11',
        '2026-05-11',
        false,
        'Recognized for exceptional technical capability, systems thinking, and innovative project architecture contributions.',
        'تكريم رسمي للتميز الأكاديمي والابتكار البرمجي وتقديم حلول تقنية متميزة.',
        5
    ),
    (
        '30000000-0000-0000-0000-000000000006',
        'certification',
        'Certificate of English Proficiency',
        'شهادة إتقان اللغة الإنجليزية وتجاوز البرامج المتقدمة',
        'Yemen-America Language Institute (YALI)',
        'المعهد اليمني الأمريكي للغات (يالي)',
        'Sana''a, Yemen',
        'صنعاء، اليمن',
        '2024-12-15',
        '2024-12-15',
        false,
        'Demonstrated high-proficiency oral, written, and technical communication in English under accredited curricula.',
        'إتمام متطلبات الكفاءة اللغوية والتواصل المهني والتقني باللغة الإنجليزية.',
        6
    )
ON CONFLICT (id) DO UPDATE SET
    title_en = EXCLUDED.title_en,
    title_ar = EXCLUDED.title_ar,
    institution_en = EXCLUDED.institution_en,
    institution_ar = EXCLUDED.institution_ar,
    description_en = EXCLUDED.description_en,
    description_ar = EXCLUDED.description_ar,
    display_order = EXCLUDED.display_order;

-- 6. Skills Table Seed
INSERT INTO public.skills (id, category, name_en, name_ar, proficiency_level, display_order) VALUES
    ('40000000-0000-0000-0000-000000000001', 'Engineering', 'Systems Architecture & UML', 'معمارية الأنظمة والتصميم الهيكلي', 92, 1),
    ('40000000-0000-0000-0000-000000000002', 'Programming', 'C# & .NET Enterprise Dev', 'تطوير التطبيقات بـ C# و.NET', 90, 2),
    ('40000000-0000-0000-0000-000000000003', 'Database', 'Oracle Database & SQL', 'قواعد بيانات أوراكل واستعلامات SQL', 88, 3),
    ('40000000-0000-0000-0000-000000000004', 'AI & ML', 'Python & Metaheuristics', 'بايثون والخوارزميات الذكية', 85, 4),
    ('40000000-0000-0000-0000-000000000005', 'Web & Cloud', 'TypeScript & Next.js Systems', 'هندسة الويب بـ TypeScript وNext.js', 90, 5)
ON CONFLICT (id) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    proficiency_level = EXCLUDED.proficiency_level,
    display_order = EXCLUDED.display_order;
